package io.tux.wallet.testnet.model.createEntropy

data class EntropyResponse(
    val chain_code: String,
    val compressed: String,
    val cryptocurrency: String,
    val entropy: String?,
    val finger_print: String,
    val hash: String,
    val language: String,
    val mnemonic: String?,
    val network: String,
    val addresses: Addresses?,
    val wif: String?,
    val ethereumaddress: String?,
    val ethereum_private_key: String?,
//    val private_key: String,
    val passphrase: Any,
    val path: String,
    val private_key: String?,
    val public_key: String,
    val root_xprivate_key: String,
    val root_xpublic_key: String,
    val seed: String,
    val semantic: String,
    val strength: Int,
    val symbol: String,
    val uncompressed: String,
    val xprivate_key: String,
    val xpublic_key: String,
    val addresses_bch: Addresses?,
    val addresses_ltc: Addresses?,
    val wif_bch: String,
    val wif_ltc: String?,
)